services:
  - type: web
    name: building-ml-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: PIP_DEFAULT_TIMEOUT
        value: "600"
      - key: FLASK_ENV
        value: production
    numInstances: 1
    region: oregon
    plan: free

  - type: web
    name: safety-skin-api
    env: python
    buildCommand: pip install -r safety/requirements.txt
    startCommand: uvicorn safety.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: PIP_DEFAULT_TIMEOUT
        value: "600"
    numInstances: 1
    region: oregon
    plan: free
